apiVersion: v2
name: alloy-operator-wrapper
description: Wrapper chart to install alloy-operator via Helm
type: application
version: 0.1.0

dependencies:
  - name: alloy-operator
    version: "0.5.3"
    repository: https://grafana.github.io/helm-charts/
