apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/cmoreira-dev/gitops.grafana.git
    targetRevision: main
    path: kustomize/alloy
  destination:
    server: https://kubernetes.default.svc
    namespace: alloy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true